### ISSUE TITLE
Schaduw onder de nummers

### ISSUE THREAD

**Issue by JEDoedens** [rodicornelisse/FrontendD#8]
Is dat een schaduw onder de nummers of een extra lijn het ziet er in elk geval heel heftig uit. 
Deze is chill er is een site waar je zelf je schaduw kan bepalen en uitzoeken. Maar ik gebruik standaard deze meestal is deze chill.
  box-shadow: 0 10px 30px 0 rgba(35, 31, 32, .1);

**Comment by rodicornelisse** [comment]
done
